#!/bin/sh

killall picom crond sxhkd pipewire wireplumber xbanish gammastep sb

setxkbmap -layout fr -variant us -option caps:none
#xrandr --dpi 140 --output HDMI-0 --pos 2560x360\
#	--output DP-2 --mode 2560x1440 --rate 120 --primary
randwp
#crond -f "$XDG_CONFIG_HOME/crontab"
xrdb "$XDG_CONFIG_HOME/sx/gruvbox-dark"

# systemd default
#pipewire &
#librespot-cfg &

# systemd graphical
#sxhkd &
#gammastep &
#picom -b --backend xrender
#sb -b
#sh -c "sleep 3; kill -10 $(pidof sb)" &

# not started
#xbanish &

exec dwm
