#!/bin/sh

killall picom scron sxhkd pipewire wireplumber xbanish redshift dwmblocks

if [ "$(xrandr | awk '/DP-2/ {print $2}')" = 'connected' ]; then
	xrandr --output LVDS-1 --off
else
	picom -b
fi

setxkbmap fr us
xrandr --dpi 100
randwp
scron -f "$XDG_CONFIG_HOME/crontab"
themeswap dracula

sxhkd &
pipewire &
xbanish &
redshift &
sleep 1s; dwmblocks &

exec dwm
