# This file was originally generated by ‘nixos-generate-config’
{ config, lib, ... }:
let
  inherit (lib.filesystem) GiB;
in
{
  boot = {
    initrd.availableKernelModules = [
      "uhci_hcd"
      "ehci_pci"
      "ahci"
      "usb_storage"
      "sd_mod"
    ];

    kernelParams = [
      # https://wiki.freebsd.org/ZFSTuningGuide
      # https://docs-archive.freebsd.org/doc/8.4-RELEASE/usr/share/doc/freebsd/en_US.ISO8859-1/books/handbook/filesystems-zfs.html
      # 1GB minimum
      # 1GB of RAM per 1TB of storage
      # 5GB of RAM per 1TB of storage with dedup
      "zfs.zfs_arc_max=${toString (2 * GiB)}"
    ];

    # List of zpools to import at boot time, needed if not using legacy mountpoints
    # zfs.extraPools = ["zpool"];
  };

  # https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS.html
  # zpool options:
  #   ashift=12 (depends on the drive & cannot be changed)
  #
  #   compression=on ("on" corresponds to the best algorithm aka lz4)
  #   dedup=on (maybe only on for /nix, /!\ roughly -15% performance)
  #   atime=off
  #   relatime=on (note that relatime=on requires atime=on)
  #   xattr=sa
  #   acltype=posixacl
  #   normalization=none (use formD for compatibility with how macOS handles unicode)
  #   autotrim=off (set this to on if using a modern nvme ssd)
  #   com.sun:auto-snapshot=true (only on /home and /var)
  #   recordsize=... currently keeping default, but maybe 1M for HDDs where storing large files

  # TODO: move this to notes or disko or idk but please this line is too long,
  # also where is the quick install guide for the rest of the partitions
  # Create a reserved partition with 10% of the total disk capacity
  # zfs create -o refreservation=$(printf '%s * 0.1' "$(zpool get size -pj | jq -r .pools.zpool.properties.size.value)" | bc | numfmt --to=iec) -o mountpoint=none zpool/reserved

  fileSystems = {
    "/" = {
      device = "zpool/root";
      fsType = "zfs";
      # The zfsutil option is needed when mounting ZFS datasets without legacy mountpoints
      # option = [ "zfsutil" ];
    };

    "/nix" = {
      device = "zpool/nix";
      fsType = "zfs";
    };

    "/var" = {
      device = "zpool/var";
      fsType = "zfs";
    };

    "/home" = {
      device = "zpool/home";
      fsType = "zfs";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/8224-B0EA";
      fsType = "vfat";
      options = [
        "noatime"
        "nodev"
        "nosuid"
        "noexec"
        "fmask=0022"
        "dmask=0022"
      ];
    };
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/279e9b8b-02";
      randomEncryption = {
        enable = true;
        cipher = "serpent-xts-plain64";
        keySize = 512;
      };
    }
  ];

  # TODO: disko
  # https://git.disroot.org/folliehiyuki/nixconfig/src/branch/main/flake/nixos/aragorn/hardware.nix
  # https://github.com/nix-community/disko/blob/master/example/zfs.nix
  # disko.devices = {
  #   nodev."/" = {
  #     fsType = "tmpfs";
  #     mountOptions = [
  #       "defaults"
  #       "size=1G"
  #       "mode=755"
  #     ];
  #   };

  #   disk.sda = {
  #     device = "/dev/sda";
  #     # device = "/dev/disk/by-id/..."
  #     type = "disk";
  #     content = {
  #       type = "gpt"; # "msdos"?
  #     };
  #   };
  # };
}
