# File synchronization tool
{ config, ... }:
let
  inherit (builtins) attrNames filter;

  allDevices = attrNames config.hm.services.syncthing.settings.devices;
  computers = filter (dev: dev != "phone") allDevices;
in
{
  # services.syncthing.openDefaultPorts
  # 22000 is used for transfer and 21027 is used for discovery
  networking.firewall = {
    allowedTCPPorts = [ 22000 ];
    allowedUDPPorts = [
      21027
      22000
    ];
  };

  hm.services.syncthing = {
    enable = true;

    # NixOS config
    #openDefaultPorts = true;
    #dataDir = "/home/${username}";
    #group = "users";
    #user = username;

    settings = {
      # Using the ids auto-generated by syncthing
      devices = {
        X200.id = "M5EV6LF-NLTED3A-4SQTN4H-SBP2NDA-QDQQD3V-O6TIU35-M6OZJZN-7WTHKAW";
        phone.id = "UQAFWER-6DKVSG6-PBM56WC-YVRLYAW-HRJGVKL-557EKQO-J46LK56-NTMPXAE";
      };

      # Versioning is done with ZFS :P
      # On phone I use trashcan versioning
      folders = {
        memes = {
          id = "kc8zd-bh5yk";
          label = "memes";
          path = "~/media/memes";
          type = "sendreceive";
          devices = allDevices;
        };
        quickshare = {
          id = "6g1vc-nc3v8";
          label = "quickshare";
          path = "~/media/quickshare";
          type = "sendreceive";
          devices = allDevices;
        };
        notes = {
          id = "xmywl-pqds6";
          label = "Notes";
          path = config.hm.xdg.userDirs.extraConfig.NOTES;
          type = "sendreceive";
          devices = allDevices;
        };
        quand-calendar = {
          id = "quand-calendar";
          label = "quand-calendar";
          path = "${config.hm.xdg.dataHome}/quand";
          type = "sendreceive";
          devices = computers;
        };
        newsboat-urls = {
          id = "newsboat-urls";
          label = "newsboat-urls";
          path = "${config.hm.xdg.configHome}/newsboat";
          type = "sendreceive";
          devices = computers;
        };
      };

      options = {
        urAccepted = -1;
      };
    };
  };
}
