# This file was originally generated by ‘nixos-generate-config’
{ config, ... }:
{
  # # I used to `modprobe dell-smm-hwmon ignore_dmi=1`
  # # but it seems to work (`sensors`) without it so idk
  # boot.extraModeprobeConfig = ''
  #   options dell-smm-hwmon ignore_dmi=1
  # '';

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/81668174-843e-4083-a2cb-1bc8b5ac3bf0";
      fsType = "btrfs";
      options = [
        "subvol=root"
        "compress=zstd"
        "noatime"
      ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/81668174-843e-4083-a2cb-1bc8b5ac3bf0";
      fsType = "btrfs";
      options = [
        "subvol=home"
        "compress=zstd"
        "noatime"
      ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/81668174-843e-4083-a2cb-1bc8b5ac3bf0";
      fsType = "btrfs";
      options = [
        "subvol=nix"
        "compress=zstd"
        "noatime" # kinda important
      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/5C77-BD85";
      fsType = "vfat";
      options = [
        # "noatime"
        # "nodev"
        # "nosuid"
        # "noexec"
        "fmask=0022"
        "dmask=0022"
      ];
    };

    # "/ssd" = {
    #   device = "/dev/disk/by-uuid/278e43c9-34a9-402f-8033-d452814954fc";
    #   fsType = "btrfs";
    #   options = [
    #     "subvol=ssd"
    #     "compress=zstd"
    #     "noatime"
    #   ];
    # };

    "/storage" = {
      device = "/dev/disk/by-uuid/b1bfaa92-e9ee-483e-96b1-aaf6c123af42";
      fsType = "ext4";
      # options = [ "relatime" ];
    };
  };

  swapDevices = [ ];

  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.legacy_580;
    open = false;
    powerManagement.enable = false; # not supported
  };
}
