[manager]
prepend_keymap = [
	{ on = "l", run = "plugin bypass smart_enter", desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory" },
	{ on = "h", run = "plugin bypass reverse", desc = "Recursively enter parent directory, skipping parents with only a single subdirectory" },
	{ on = "p", run = "plugin --sync smart-paste", desc = "Paste into the hovered directory or CWD" },
	{ on = "T", run = "plugin --sync hide-preview", desc = "Hide or show preview" },
	{ on = "<C-n>", run = '''shell 'dragon-drop -x -T "$1"' --confirm''' },
	{ on = [ "g", "c" ], run = "cd $XDG_CONFIG_HOME", desc = "Go to the config directory" },
	{ on = [ "g", "d" ], run = "cd $XDG_DOWNLOAD_DIR",   desc = "Go to the downloads directory" },
	{ on = "<backspace>", run = "remove", desc = "Trash selected files" },
	{ on = "o", run = '''shell 'plumber "$1"' --confirm''', desc = "Open selected files" },
	{ on = "<Enter>", run = '''shell 'plumber "$1"' --confirm''', desc = "Open selected files" },
	{ on = "w", run = '''shell 'env IGNORE="" randwp "$1"' --confirm''', desc = "Set wallpaper" },
	{ on = "W", run = "tasks_show", desc = "Show task manager" },
	{ on = "<C-z>", run = "noop" },
	{ on = "C", run = "plugin ouch zip", desc = "Compress with ouch" },
]
