#!/bin/sh

# ROOTCMD not required for some system commands
for command in iftop mount umount fdisk cryptsetup modprobe pacman shutdown poweroff reboot ; do
	alias $command="$ROOTCMD $command"
done; unset command

# edit config files and stuff
alias cf="cd $XDG_CONFIG_HOME"
alias cfv="cd $XDG_CONFIG_HOME/nvim"
alias cfz="v $ZDOTDIR/.zshrc"
alias cfe="v $ZDOTDIR/.zshenv"
alias cfa="v $ZDOTDIR/aliasrc"
alias cfx="v $XDG_CONFIG_HOME/sx/sxrc"
alias cfn="v $XDG_CONFIG_HOME/newsboat/config"
alias cfu="v $XDG_CONFIG_HOME/newsboat/urls"
alias cfb="cd $XDG_CONFIG_HOME/dwmblocks/blocks"
alias dt="cd $XDG_DATA_HOME"
alias pkg="v $XDG_DATA_HOME/packages/packages"
alias aur="v $XDG_DATA_HOME/packages/packages.aur"
alias d="cd $XDG_DOWNLOAD_DIR"
alias m="cd $XDG_MUSIC_DIR"
alias pp="cd $XDG_PICTURES_DIR"
alias psc="cd $XDG_PICTURES_DIR/screenshots"
alias vv="cd $XDG_VIDEOS_DIR"
alias ww="cd $XDG_DATA_HOME/wallpapers"
alias n="lf $XDG_DATA_HOME/notes"
alias nn="cd $XDG_DATA_HOME/notes"
alias sc="cd $HOME/.local/bin"

# shorter name and basic stuff changed
[ -x "$(command -v nvim)" ] && alias vimdiff="nvim -d"
alias v="$EDITOR"
alias vim="$EDITOR"
alias suvi="$ROOTCMD $EDITOR"
alias suvim="suvi"
alias make="make PREFIX=$HOME/.local" # ROOTCMD not required for make
alias p="pacman"
alias lf="lfub"
alias :q="exit"
alias :Q="exit"
alias bc="bc -ql"
alias sxiv="sxiv -a"
alias z="zathura"
alias pdf="swallow zathura"
alias timer="termdown"
alias video-dlp="yt-dlp -f 'bv' -o '%(title)s [%(id)s].%(ext)s'"
alias music-dlp="yt-dlp -f 'ba' -x --embed-thumbnail --audio-format mp3 \
	--postprocessor-args \"-ar 44100\" -o '%(playlist_index)s - %(title)s [%(id)s].%(ext)s'"
alias paint="pinta"
alias python="python3"
alias py="python"
alias 2048="swallow gnome-2048"
alias nb="newsboat"

# verbosity and colors
alias rm="rm -vI"
alias rmdir="rmdir -v"
alias cp="cp -riv"
alias mv="mv -iv"
alias mkdir="mkdir -pv"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip --color=auto"
alias ls="exa --icons --group-directories-first"
alias sl="ls"
alias ll="ls -lh"
alias la="ls -a"
alias l="ls -lah"
alias tree="ls --tree"
alias cat="bat"
alias du="dust -r"
alias duf="duf -hide special"

# git
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit -a" # replace -a with -v for verbosity
alias gcm="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gr="git restore"
alias grs="gr --staged"
alias gb="git branch"
alias gd="git diff"
alias gac="ga . && gc"
alias gacp="ga . && gc && gp"

# music
alias pause="musiccmd pause"
alias play="musiccmd play" # This does the same thing as pause
alias next="musiccmd next"
alias prev="musiccmd prev"
alias stop="musiccmd stop"
alias update="kill -43 $(pidof dwmblocks)"
alias vol="musiccmd volume" # put the volume you want in arg like vol 50
