#!/bin/sh

# doas not required for some system commands
for command in mount umount sv pacman updatedb shutdown poweroff reboot ; do
	alias $command="$ROOTCMD $command"
done; unset command

# bad memory
alias calc="bc"
alias 7zip="7z"
alias p7zip="7z"
alias calendar="when c"
alias battery="db_battery"
alias img="sxiv -a"
alias yt="swallow mpv"
#alias yt="mpv --ytdl-format=22 "
alias audio="mpv --no-video --loop-playlist"
alias shuffle="audio --shuffle"
alias pdf="swallow zathura"
alias md="glow"
alias timer="termdown"
alias video-dlp="yt-dlp -f 'bv' -o '%(title)s [%(id)s].%(ext)s'"
alias music-dlp="yt-dlp -f 'ba' -x --embed-thumbnail --audio-format mp3 -o '%(playlist_index)s - %(title)s [%(id)s].%(ext)s'"
alias paint="pinta"

# misc
alias v="$EDITOR"
alias vim="$EDITOR"
alias suvi="$ROOTCMD $EDITOR"
alias python="python3"
alias p="pacman"
alias :q="exit"
alias :Q="exit"
#alias cs="cd"
alias 2048="swallow gnome-2048"
alias lf="lfub"

# verbosity and stuff
alias rm="rm -vI"
alias rmdir="rmdir -v"
alias cp="cp -riv"
alias mv="mv -iv"
alias mkdir="mkdir -pv"
#alias man="manpdf"

# colors
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip --color=auto"

# ls
alias ls="exa --icons --group-directories-first"
alias sl="ls"
alias la="ls -a"
alias ll="ls -lah"
alias tree="ls --tree"

# git
alias gs="git status"
alias gp="git pull"
alias ga="git add"
alias gac="git add . && git commit -a"
alias gacp="git add . && git commit -a && git push"

# edit config files
alias vimrc="cd $XDG_CONFIG_HOME/nvim"
alias zshrc="v $XDG_CONFIG_HOME/shell/.zshrc"
alias aliasrc="v $XDG_CONFIG_HOME/shell/aliasrc"
alias paliasrc="v $XDG_CONFIG_HOME/shell/paliasrc"
alias sxrc="v $XDG_CONFIG_HOME/sx/sxrc"
alias packages="v $XDG_DATA_HOME/packages/packages"
alias AUR="v $XDG_DATA_HOME/packages/packages.aur"
alias aur="AUR"
alias config="cd $XDG_CONFIG_HOME"
