#!/bin/zsh

# Add ~/.local/bin to $PATH
export PATH="$HOME/.local/bin/dwmblocks:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="ungoogled-chromium"
export ROOTCMD="doas"

# ~/ Clean-up:
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.local/etc"
export XDG_CACHE_HOME="$HOME/.local/var/cache"
export XDG_STATE_HOME="$HOME/.local/var/state"
export XDG_DESKTOP_DIR="$HOME"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pictures"
export XDG_VIDEOS_DIR="$HOME/videos"
export ZDOTDIR="$XDG_CONFIG_HOME/shell"
export GOPATH="$XDG_DATA_HOME/go"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec sx
