# Based on https://github.com/diniamo/niqspkgs/blob/main/.github/workflows/cachix.yaml
name: Build uncached packages

on:
  workflow_dispatch:
  push:
    branches:
      - nixos

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  find-uncached:
    runs-on: ubuntu-latest
    outputs:
      uncached: ${{ steps.get-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v6

      - name: "Set up Nix"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - name: "Find packages missing in the cache"
        id: get-packages
        run: |
          set -euo pipefail

          packages='[]'
          while read -r package; do
            path="$(nix eval --raw ".#$package" 2>/dev/null)"
            if ! nix path-info --store https://ratakor.cachix.org "$path" &>/dev/null; then
              echo "Building $package"
              packages="$(echo -n "$packages" | jq --arg package "$package" --compact-output '. + [$package]')"
            fi
          done < <(nix flake show --json 2>/dev/null | jq --raw-output '.packages."x86_64-linux" | keys_unsorted | map("packages.x86_64-linux.\(.)") | .[]')

          echo -n "packages=$packages" >> "$GITHUB_OUTPUT"

  build-uncached:
    needs: find-uncached
    if: needs.find-uncached.outputs.uncached != '[]'
    strategy:
      matrix:
        package: ${{ fromJSON(needs.find-uncached.outputs.uncached) }}
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Nix"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - name: "Set up Cachix"
        uses: cachix/cachix-action@v17
        with:
          name: ratakor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix build "github:${{ github.repository }}/${{ github.ref }}#${{ matrix.package }}"

  deploy-docs:
    needs: [find-uncached, build-uncached]
    if: |
      always() &&
      needs.find-uncached.result == 'success' &&
      contains(needs.find-uncached.outputs.uncached, 'packages.x86_64-linux.docs') &&
      needs.build-uncached.result == 'success'
    uses: ./.github/workflows/docs.yml
    secrets: inherit
