name: Check flake

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - nixos/master

permissions:
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: "Set up Nix"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - name: "Set up Cachix"
        uses: cachix/cachix-action@v17
        with:
          name: ratakor

      - name: "Check Nix flake"
        run: nix flake check
