name: Update sources

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 1 * * 6" # At 01:00 on Saturday.

permissions:
  contents: read
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          ref: nixos/master
          token: "${{ secrets.FLAKE_UPDATE_PAT }}"

      - name: "Set up Nix"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - name: "Set up Cachix"
        uses: cachix/cachix-action@v17
        with:
          name: ratakor

      - name: "Update sources"
        run: nix run .#tack -- update

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci: update sources"
